package lovera.kualpostinvou.modelos.constantes;

public enum Especialidades {

    TODAS("todas"),
    DST_AIDS("DST/AIDS"),
    NEFROLOGIA("NEFROLOGIA"),
    OSTEOGENESIS_IMPERFECTA("OSTEOGENESIS IMPERFECTA"),
    TRANSEXUALIZADOR("TRANSEXUALIZADOR"),
    NEUROLOGIA_NEUROCIRURGIA("NEUROLOGIA/NEUROCIRURGIA"),
    PNEUMOLOGIA("PNEUMOLOGIA"),
    TRANSPLANTES("TRANSPLANTES"),
    ATENCAO_SAUDE_AUDITIVA("ATENCAO A SAUDE AUDITIVA"),
    UNIDADE_TERAPIA_INTENSIVA("UNIDADE TERAPIA INTENSIVA"),
    TRAUMATO_ORTOPEDIA("TRAUMATO-ORTOPEDIA"),
    QUEIMADOS("QUEIMADOS"),
    ATENCAO_OBESIDADE_GRAVE("ATENCAO A OBESIDADE GRAVE"),
    ONCOLOGIA("ONCOLOGIA"),
    VIDEOCIRURGIAS("VIDEOCIRURGIAS"),
    ATENCAO_SAUDE_OCULAR("ATENCAO A SAUDE OCULAR"),
    ATENCAO_SAUDE_MENTAL("ATENCAO A SAUDE MENTAL"),
    HOSPITAL_DIA("HOSPITAL DIA"),
    DOR_CRONICA("DOR CRONICA"),
    PLANEJAMENTO_FAMILIAR_ESTERELIZACAO("PLANEJAMENTO FAMILIAR/ESTERELIZACAO"),
    CUIDADOS_PROLONGADOS("CUIDADOS PROLONGADOS"),
    TERAPIA_NUTRICIONAL("TERAPIA NUTRICIONAL"),
    REABILITACAO("REABILITACAO"),
    UNIDADE_CUIDADOS_INTERMEDIARIOS_NEONATAL("UNIDADE DE CUIDADOS INTERMEDIARIOS NEONATAL"),
    ATENCAO_A_SAUDE_BUCAL("ATENCAO A SAUDE BUCAL"),
    INTERNACAO_DOMICILIAR("INTERNACAO DOMICILIAR"),
    URGENCIA("URGENCIA"),
    ATENCAO_AO_IDOSO("ATENCAO AO IDOSO"),
    CARDIOVASCULAR("CARDIOVASCULAR"),
    MATERNO_INFANTIL("MATERNO INFANTIL"),
    PROGRAMA_MAMOGRAFIA_MOVEL("PROGRAMA DA MAMOGRAFIA MÓVEL");

    private String texto;

    Especialidades(String texto) {
        this.texto = texto;
    }

    public String getTexto() {
        return texto;
    }

    public static String[] getTextos(){
        Especialidades[] values = Especialidades.values();
        String[] textos = new String[values.length];

        for(int i = 0; i < values.length; i++){
            textos[i] = values[i].getTexto();
        }
        return textos;
    }
}
